gedit drivers/hid/hid-core.c
gedit drivers/iio/adc/qcom-rradc.c
gedit drivers/media/platform/msm/camera_v2/sensor/flash/msm_flash.c
gedit drivers/media/platform/msm/sde/rotator/sde_rotator_r3.c
gedit drivers/media/platform/msm/vidc/msm_vidc_common.c
gedit drivers/mmc/core/sdio_cis.c
gedit drivers/power/power_supply_sysfs.c
gedit drivers/power/supply/qcom/fg-core.h
gedit drivers/power/supply/qcom/fg-memif.c
gedit drivers/power/supply/qcom/fg-reg.h
gedit drivers/power/supply/qcom/fg-util.c
gedit drivers/power/supply/qcom/qpnp-fg-gen3.c
gedit drivers/soc/qcom/msm_performance.c
gedit drivers/staging/android/ion/msm/msm_ion.c
gedit drivers/staging/android/lowmemorykiller.c
gedit drivers/video/console/vgacon.c
gedit drivers/video/fbdev/msm/mdss_dsi.c
gedit drivers/video/fbdev/msm/mdss_dsi_host.c
gedit drivers/video/fbdev/msm/mdss_dsi_panel.c
gedit fs/namei.c
gedit include/linux/power_supply.h
gedit include/sound/apr_audio-v2.h
gedit include/sound/q6afe-v2.h
gedit kernel/sched/sched.h
gedit sound/soc/codecs/sdm660_cdc/msm-analog-cdc.c
gedit sound/soc/msm/qdsp6v2/msm-pcm-routing-v2.c
gedit sound/soc/msm/qdsp6v2/q6afe.c
gedit sound/soc/msm/qdsp6v2/q6audio-v2.c
gedit sound/soc/msm/sdm660-internal.c

